package ahorcado;

public class Palabras {
	
	public static String generarPalabra(int largo) {
		String palabra = "";
		
		String[] cuatro = {"duda", "dual", "dote", "echo", "eden", "edad", "ecos", "eche", "echa", "eñes",
			    "duro", "duos", "dota", "doce", "doña", "diva", "dira", "dios", "dino",
			    "dime", "done", "dore", "dora", "domo", "dome", "dolo", "edil", "dijo",
			    "euro", "eter", "esto", "esos", "eses", "fase", "faro", "fama", "faca", "falo",
			    "fajo", "erre", "ella", "ende", "emir", "emes", "ello", "elfo", "eles",
			    "ejes", "erra", "eros", "eres", "eras", "eran", "ente", "dima",
			    "dije", "cree", "crie", "crin", "cuco", "cubo", "cuba", "cuña", "cruz", "cola",
			    "coja", "coma", "codo", "come", "coro", "cota", "cosa", "copa", "cono", "como",
			    "digo", "dato", "dedo", "deja", "dala", "diño", "diga", "diez",
			    "dice", "dias", "dial", "diñe", "deje", "demo", "dele", "dejo", "dama", "dais",
			    "cura", "cupo", "culo", "daga", "dado", "daño", "cuyo", "cuya", "halo", "hala",
			    "haya", "hago", "haga", "hada", "hace", "guru", "hiel", "higo", "goza", "gran",
			    "gozo", "goyo", "groa", "goya", "gota", "gong", "goma", "golf"};
		
		String[] cinco = {"abeto", "actor", "aguas", "agudo", "alado", "albas", "altar", "antón", "atizo", "avala",
			    "avión", "azul", "babas", "bacas", "bache", "bajes", "balas", "bebés", "belén", "berto",
			    "bicho", "bizco", "bueno", "busca", "caída", "calar", "calas", "calca", "calla", "calma",
			    "camba", "campo", "canas", "cantos", "capto", "caras", "carlo", "carro", "casas", "catar",
			    "cejas", "celia", "cenas", "cepas", "cerca", "cerco", "cerdo", "chile", "china", "ciego",
			    "cines", "citas", "clara", "clavo", "colas", "colon", "colón", "coral", "coras", "corea",
			    "corro", "cosas", "costo", "crudo", "curar", "dados", "dagas", "daños", "datos", "dejar",
			    "dejes", "denso", "dices", "divos", "dotes", "dunas", "dures", "duros", "echas", "edito",
			    "elevo", "ellos", "emulé", "emulo", "enoje", "error", "estás", "fallo", "falto", "feria",
			    "fetos", "fijos", "filas", "filia", "finca", "gafas", "galas", "gales", "galos", "ganas",
			    "ganes", "gases", "gasto", "giras", "gordo", "gorro", "grave", "grito", "hacer", "halos",
			    "hasta", "heces", "hielo", "ideas", "india", "inflo", "islas", "jefas", "jerga", "josué",
			    "julio", "manía", "marca", "marco", "martí", "maría", "melón", "menos", "meter", "metro",
			    "moler", "monte", "morir", "nadar", "narro", "natas", "naves", "necio", "niños", "notas",
			    "nubes", "obras", "ocios", "ollas", "ondas", "onzas", "opera", "otros", "ovulo", "oírte",
			    "palas", "parís", "pedir", "pelea", "pelos", "peras", "perro", "pesos", "pilas", "pinto",
			    "poder", "qatar", "quedo", "quema", "quito", "reloj", "rubio", "rasco", "ratas", "ratos",
			    "redes", "remar", "renos", "renta", "sabio", "sacar", "salir", "selva", "sanar", "sopas",
			    "secar", "serio", "sitúo", "sobar", "sonar", "subir", "sucio", "siete", "tabla", "tacos",
			    "tania", "tapas", "tazas", "telón", "tener", "tenis", "terco", "terso", "texas", "tipos",
			    "tiras", "todas", "todos", "tomar", "tomás", "tonos", "tonto", "toque", "torpe", "trote",
			    "vacas", "vagos", "valer", "valor", "veces", "vedas", "velas", "vemos", "venas", "venir",
			    "verde", "viera", "vigas", "vinos", "vivir", "volar", "votar", "yates", "yemas", "yemen",
			    "yendo", "yenes", "yesca", "yogur", "yugos", "zonas", "zorro", "zurdo"};
		
		String[] seis = {"abetos", "abriga", "abuela", "acceso", "aceras", "aclamó", "actriz",
			    "acuden", "ademán", "además", "adorna", "afanes", "afluir", "agente",
			    "agonía", "aguzar", "ahonda", "aislar", "aladas", "alcoba", "aldeas",
			    "alerta", "alhaja", "alivió", "alteró", "altura", "alzado", "amigas",
			    "andaba", "anhelo", "animal", "aparte", "apenas", "aplomo", "apurar",
			    "armada", "arrobo", "asador", "asalto", "asomar", "astral", "atadas",
			    "ataque", "atener", "atenta", "atrevo", "aunque", "aurora", "avance",
			    "avidez", "avisar", "ayudas", "azúcar", "bacilo", "bajará", "balcón",
			    "barbas", "barniz", "basado", "bastón", "bebida", "besado", "biblia",
			    "bistec", "blanca", "bloque", "bolita", "bondad", "bonita", "bordea",
			    "borlas", "borrar", "bosque", "botica", "breves", "brillo", "brindó",
			    "bromas", "brotes", "brusca", "brutal", "buenas", "buenos", "buscan",
			    "butaca", "básico", "cabría", "cabeza", "cambia", "cascos", "casita",
			    "casona", "castas", "caudal", "causar", "calaba", "callar", "calles",
			    "calmar", "cayera", "cedido", "cegado", "celina", "celosa", "darían",
			    "darles", "darlos", "darnos", "danzas", "datara", "debajo", "debían",
			    "debido", "decidí", "decías", "decían", "dejaba", "dejará", "discos",
			    "dioses", "dormía", "dormir", "dotado", "dramas", "dudaba", "dulces",
			    "dureza", "emigra", "empapé", "empecé", "empezó", "empina", "empinó",
			    "emplea", "empleo", "empujó", "encaje", "encima", "encina", "enfada",
			    "enfado", "enfría", "enlazó", "entera", "entere", "entero", "enteró",
			    "estaca", "europa", "evitar", "evocan", "evocar", "exacta", "exacto",
			    "exalta", "famosa", "farsas", "fatiga", "febril", "felipe", "fervor",
			    "festón", "fiados", "fiebre", "fieles", "fiesta", "figura", "fijaba",
			    "fijara", "filtro", "fingir", "finura", "firmes", "flecha", "flecos",
			    "flotar", "fluido", "fogosa", "fondos", "forman", "formas", "franca",
			    "franja", "frentes", "fresas", "fresca", "frutas", "frágil", "fuegos",
			    "fuente", "fueran", "fueras", "fueron", "fuerte", "fuerza", "fuimos",
			    "fundas", "fundía", "futura", "galope", "ganado", "garras", "gestos",
			    "gloria", "goloso", "grafía", "granos", "graves", "grises", "gritar",
			    "habido", "hablan", "hablar", "habrán", "habría", "habéis", "habían",
			    "habías", "hacían", "halago", "hallar", "harían", "hechas", "hechos",
			    "helaba", "helada", "helado", "herida", "herido", "hierro", "hipaba",
			    "huecos", "huelen", "huella", "huerto", "huesos", "huevos", "huiría",
			    "idiota", "ignora", "ignoro", "imagen", "imitar", "impide", "impuso",
			    "indica", "índice", "indicó", "inerte", "infiel", "inflar", "infusa",
			    "inglés", "inició", "invita", "invitó", "inútil", "jardín", "jarrón",
			    "jauría", "jeanne", "jóquey", "juegan", "juegos", "jugaba", "jugase",
			    "juicio", "julián", "manía", "marca", "marco", "martí", "maría", "melón",
			    "menos", "meter", "metro", "moler", "monte", "morir", "nadar", "narro",
			    "natas", "naves", "necio", "niños", "notas", "nubes", "obras", "ocios",
			    "ollas", "ondas", "onzas", "opera", "otros", "ovulo", "oírte", "palas",
			    "parís", "pedir", "pelea", "pelos", "peras", "perro"};
				
		String[] siete = {"acombes", "becamos", "bucemos", "cabemos", 
	            "calimbo", "calumbo", "cambeis", "cambero", "cambeto",
	            "cambies", "cambios", "cambote", "cambute", "cebamos",
	            "cembrío", "címbalo", "címblar", "címblas", "calimbe",
	            "címbles", "címbros", "colimba", "combaís", "combare",
	            "combase", "combate", "combati", "combeis", "comible",
	            "cubismo", "cumbari", "cumbeas", "cumbias", "cumbral",
	            "cumbres", "embarco", "embauco", "embicar", "embicas",
	            "embocar", "embocas", "embosca", "embroca", "rombica",
	            "abrimos", "abromes", "abrúces", "abrúmes", "abuceis",
	            "abulico", "acerbos", "acimuts", "acometí", "acribes",
	            "acubile", "acubilo", "aerobic", "álbumes", "alcemos",
	            "almocri", "almorce", "alombes", "alumbre", "alumbro",
	            "ámbitos", "ambleis", "ambleos", "ambules", "américo",
	            "amorecí", "amueblo", "amurcos", "asombre", "atomice",
	            "bacilos", "baculos", "bálemos", "balices", "báltico",
	            "barceos", "baremos", "baricos", "bascule", "básculo",
	            "baticor", "batimos", "batueco", "bautice", "becario",
	            "belicas", "belicos", "beocias", "bercial", "besucar",
	            "béticas", "béticos", "bicales", "bilmare", "bilmase",
	            "bilocar", "bilocas", "bimetal", "biromes", "biscote",
	            "bisecar", "bismuto", "bisulca", "bisulco", "bisurco",
	            "bitamos", "bitemos", "bocais",  "blocare", "blocase",
	            "bocales", "bocarte", "boceais", "bocelar", "bocelas",
	            "boceras", "boricua", "borucas", "borusca", "bostica",
	            "boticas", "braceos", "brameis", "breamos", "broceas",
	            "broceis", "broculi", "bromais", "bromase", "bromeas",
	            "bromeis", "bruceis", "brucita", "brumais", "brumase",
	            "brumeis", "brumosa", "bucales", "bucares", "bucaros",
	            "buceais", "buceros", "buclosa", "bulecos", "bulicas",
	            "bulicos", "buracos", "buscare", "butomea", "caberos",
	            "cablero", "cablote", "cabreis", "cabreos", "cabrios",
	            "cabrito", "cabures", "caibles", "calbote", "calemos",
	            "calibes", "calibre", "calibro", "calimos", "calmeis"};
		
		String[] ocho = {"repudios", "repulida", "repulido", "repulsad", 
	            "rescinda", "rescindo", "rescolda", "resoplAD", "respaldo",
	            "responda", "respondi", "riscando", "rispando", "rodapies",
	            "rondices", "sacudion", "sacudire", "secundar", "espinado",
	            "espinuda", "espinudo", "espirado", "espoliad", "rescaldo",
	            "espondil", "espundia", "increado", "incusado", "indecora",
	            "inoculad", "iracundo", "lapideos", "licuados", "licuando",
	            "linceado", "lucidora", "luciendo", "lucrados", "lucrando",
	            "ludicras", "ludicros", "necrosad", "nordicas", "nucleido",
	            "ocluidas", "padrinos", "padrones", "palurdos", "pandeiro",
	            "panderos", "pariendo", "parodien", "parodies", "pedilona",
	            "peinador", "peinados", "pelidura", "peliduro", "pendolas",
	            "pendrais", "pendular", "pendulas", "pendulos", "pensador",
	            "perdonas", "perlados", "perlando", "persuadi", "persuado",
	            "descrian", "desculan", "descular", "deslucia", "deslucio",
	            "deslucir", "desnucar", "desopila", "desopina", "desuncia",
	            "desuncio", "desuncir", "desurcan", "diaspero",
	            "dilacero", "discaren", "discaron", "disepalo", "dislocan",
	            "dislocar", "disparen", "disponer", "diucones", "dolarice",
	            "sepulcro", "sincopal", "sincopar", "suplican", "suplicar",
	            "acidulen", "acidules", "acidulos", "acleidos", "acordeis",
	            "acuerdos", "acurdeis", "adocilen", "adociles", "adonices",
	            "adulceis", "adulcire", "alipedos", "aprendio", "ascendio",
	            "asciendo", "asconder", "calderin", "calderon", "calderos",
	            "caldreis", "caliendo", "candiles", "candores", "cardenos",
	            "cardones", "cariedon", "carnudos", "caudinos", "caudones",
	            "cedrinas", "cedrinos", "cedulais", "celindas", "cendalis",
	            "cendrais", "censador", "censurad", "cerdonas", "cerionda",
	            "brucitas", "brumales", "brumaste", "bruscate", "brutesca",
	            "brutesco", "burlamos", "burlemos", "burlesca", "burlesco",
	            "butomeas", "cabestro", "cableros", "cablotes", "cabresto",
	            "cabriole", "cabritos", "calbotes", "calibres", "calimote",
	            "camelios", "camisero", "camisote", "caribues", "cariemos",
	            "carlismo", "celibato", "celtismo", "ciaremos", "clamores",
	            "cleuasmo", "clubista", "cobraste", "cobreais", "coimeras",
	            "colemias", "colimare", "colimase", "colmared", "colmaste",
	            "colmates", "comerias", "cometais", "cometias", "comieras",
	            "comisare", "comisura", "comitres", "corbetas", "creiamos",
	            "cribaste", "cribelos", "cromaste", "cuamiles", "cuberias",
	            "cubierta", "cubierto", "cubilare", "cubilase", "cubilote",
	            "cubitera", "cubriste", "culeamos", "culebras", "cultismo",
	            "curables", "curtamos", "curtimos", "emasculo", "embolais",
	            "embolias", "embolsar", "embostar", "embotais", "embustia",
	            "embustio", "embustir", "embutais", "embutiar", "embutias",
	            "embutira", "escatimo", "estambro", "euboicas", "labremos",
	            "lacremos", "lactemos", "lambiste", "lembario", "leucomas",
	            "libracos", "libramos", "libremos", "libresca", "libresco",
	            "licuamos", "licuemos", "lubricas", "lubricos", "luciamos",
	            "lucramos", "lucremos", "lumbares", "lumbrosa", "lumiacos",
	            "maculeis", "maiceros", "malcorte", "malcries", "marciste",
	            "maruecos", "masicote", "masturbe", "masturbo", "matrices",
	            "metalico", "metricas", "metricos", "mirtaceo", "mocareis",
	            "moralice", "morcales", "morcaste", "moscatel", "motacues",
	            "motrices", "mueblais", "mulatice", "musicare", "mutables",
	            "oblicuar", "oblicuas", "oblicues", "octubres", "olambres",
	            "rabiemos", "raicemos", "ralbemos", "reblamos", "rebotica",
	            "recaimos", "reclamos", "recomaís", "recomías", "rectamos",
	            "rembolsa", "remolcas", "retumbas", "retumbos", "rombales",
	            "rubiaceo", "rubicela", "rumbaste", "rumbeais", "rumiacos",
	            "sabelico", "salumbre", "simbolar", "sociable", "somatice",
	            "sometica", "sublimar", "tablemos", "tamberos", "tambores",
	            "tamboril", "tebaicos", "temblais", "temblosa", "termicas",
	            "termicos", "tiemblas", "tiemblos", "timbales", "timbrase",
	            "timbreas", "timbreos", "tocables", "trabemos", "trabucos",
	            "tracemos", "tricemos", "trocable", "trucamos", "tumbales",
	            "tumbares", "turbamos", "turbemos", "ubicares", "ubicaste",
	            "ulmaceos", "umbrales", "umbratil", "uremicas"};
		
		String[] nueve = {"capulidos", "carpiendo", "clepsidra", "conspirad", "crispando",
	            "decuplais", "desaplico", "desocupan", "desocupar", "desplacio",
	            "discrepan", "disculpan", "disculpar", "disculpen", "displacen",
	            "displacer", "drupaceos", "duplicare", "duplicase", "eclipsado",
	            "esculpida", "esculpido", "escupidor", "esparcido", "increpado",
	            "inculpado", "paloduces", "paludicos", "pandureco", "parecidos",
	            "pedicular", "pediculos", "pedicuras", "pedicuros", "pedriscal",
	            "percudais", "percudian", "percudias", "picaderos", "picadores",
	            "pincelado", "placiendo", "podrecian", "podrecias", "poncidres",
	            "preciados", "preciando", "precisado", "prelucido", "prescinda",
	            "prescindo", "procedais", "procedian", "procedias", "producian",
	            "producias", "prudencia", "recopilad", "reduplica", "reduplico",
	            "repacidos", "repicados", "repicando", "replicado", "suplicado",
	            "calepinos", "capulines", "copilaren", "copilares", "copilasen",
	            "copinares", "coplerias", "copularen", "copulares", "copulasen",
	            "corupanes", "culpareis", "cupresina", "cupresino", "encapsulo",
	            "erupciona", "escarpion", "escorpina", "esculpian", "esculpira",
	            "escupiran", "inculpare", "inculpase", "lapiceros", "necropsia",
	            "nupciales", "ocupareis", "opulencia", "paniculos", "pecuarios",
	            "pelicanos", "peluconas", "percolais", "percusion", "periconas",
	            "picarones", "piconeras", "pinaculos", "placieron", "pliocenas",
	            "polaricen", "polarices", "polcareis", "prelacion", "prelucian", 
	            "balitemos", "basculero", "baticulos", "batiremos", "bilocares",
	            "bilocarse", "bilocaste", "bimestral", "bitaremos", "blocareis",
	            "bosticare", "brutalice", "bucelario", "burilamos", "burilemos",
	            "cabrioles", "calimotes", "celibatos", "citaremos", "colimares",
	            "colimaste", "colmareis", "colmateis", "comitales", "cuartemos",
	            "cubiertas", "cubiertos", "cubilares", "cubilaste", "cubilotes",
	            "cubitales", "cubiteras", "cuiteamos", "curtiamos", "embustira",
	            "embutiras", "eructamos", "estrabico", "laburemos", "lembarios",
	            "libaremos", "liberamos", "libreamos", "lubricase", "luciremos",
	            "malcortes", "matricule", "matriculo", "metalicos", "mirtaceos",
	            "moralices", "mostrable", "mueblista", "mulatices", "oblicuare",
	            "oblicuase", "rabilemos", "rebatimos", "rebitamos", "reboticas",
	            "rebutamos", "rebutimos", "recitamos", "recluimos", "reculamos",
	            "relucimos", "remolcais", "retumbais", "reumatico", "robusteci",
	            "rubiaceos", "rubicelas", "semiculta", "semiculto", "simulacro"};
		
		String[] diez = {"culipandeo", "decuplaron", "depuracion", "despicaron", "disculpare",
	            "duplicaren", "duplicares", "duplicaron", "duplicasen", "eclipsando",
	            "erupcionad", "esculpidor", "escupidora", "increpados", "inculpados",
	            "pandurecos", "picudearon", "pincelados", "precisando", "prudencial",
	            "prudencias", "pudelacion", "reduplican", "reduplicas", "replicados",
	            "replicando", "suplicando", "copulareis", "eclipsaron", "erupcionas",
	            "esculpiran", "espiraculo", "inculpares", "opulencias", "preclusion",
	            "repliconas", "superacion", "suplicaren", "suplicaron", "adulcieron",
	            "ardinculos", "candileros", "cedularios", "cidronelas", "colindares",
	            "coludieran", "coludieras", "descularon", "desluciran", "dislocaren",
	            "duraciones", "edulcorais", "elucidaron", "enlucidora", "ensuciador",
	            "incredulas", "incredules", "irlandesco", "perindolas", "reclinados",
	            "repinaldos", "repulsando", "resudacion", "sacudieron", "secundario",
	            "inoculares", "laurencios", "nuclearios", "ondulareis", "acostumbre", 
	            "acubilemos", "bauticemos", "calibremos", "cimbaleros",	"rumeliotas",
	            "columbetas", "columbrais", "columbrase", "columbreis", "embolsicar",
	            "emborucais", "lambrucios", "lambuceros", "lubricamos", "rumbaticos",
	            "ubicaremos", "umbraticos", "alirucemos", "brutalices", "bucelarios",
	            "buitreamos", "libertamos", "licuaremos", "lubricaste", "lucieramos",
	            "matricules", "meticulosa", "oblicuares", "oblicuaste", "rebutiamos",
	            "recluiamos", "reclutamos", "reluciamos", "reumaticos", "robustecia",
	            "tamboriles", "timbaleros", "umbratiles", "locutareis", "ocultareis"};
		
		switch(largo) {
		case 4:
			palabra = cuatro[(int)Math.floor(Math.random()*cuatro.length)];
			break;
		case 5:
			palabra = cinco[(int)Math.floor(Math.random()*cinco.length)];
			break;
		case 6:
			palabra = seis[(int)Math.floor(Math.random()*seis.length)];
			break;
		case 7:
			palabra = siete[(int)Math.floor(Math.random()*siete.length)];
			break;
		case 8:
			palabra = ocho[(int)Math.floor(Math.random()*ocho.length)];
			break;
		case 9:
			palabra = nueve[(int)Math.floor(Math.random()*nueve.length)];
			break;
		case 10:
			palabra = diez[(int)Math.floor(Math.random()*diez.length)];
			break;
		}
		
		return palabra;
	}

}
